name: Issue assignment

on:
  issues:
    types: [opened, edited, labeled, unlabeled]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          assignees: cryi
          skipKeywords: wip, draft