name: Issue assignment

on:
  issues:
    types: [opened, edited, labeled, unlabeled]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: pozil/auto-assign-issue@v1
        with:
          assignees: cryi
